// flow-typed signature: 921a6b29b5743affd766230f86efb37b
// flow-typed version: <<STUB>>/node-wit_v^4.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-wit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-wit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-wit/lib/config' {
  declare module.exports: any;
}

declare module 'node-wit/lib/interactive' {
  declare module.exports: any;
}

declare module 'node-wit/lib/log' {
  declare module.exports: any;
}

declare module 'node-wit/lib/wit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-wit/index' {
  declare module.exports: $Exports<'node-wit'>;
}
declare module 'node-wit/index.js' {
  declare module.exports: $Exports<'node-wit'>;
}
declare module 'node-wit/lib/config.js' {
  declare module.exports: $Exports<'node-wit/lib/config'>;
}
declare module 'node-wit/lib/interactive.js' {
  declare module.exports: $Exports<'node-wit/lib/interactive'>;
}
declare module 'node-wit/lib/log.js' {
  declare module.exports: $Exports<'node-wit/lib/log'>;
}
declare module 'node-wit/lib/wit.js' {
  declare module.exports: $Exports<'node-wit/lib/wit'>;
}
